### ISSUE TITLE
Data persistans in docker

### ISSUE THREAD

**Issue by jwillmer** [SignalK/signalk-server#1366]
I have the following docker-compose config for signalk but on every restart my users lose the changes they did in the node-red service that they installed inside of signalk. Seams like the data is stored at a different location. Can someone tell me which location I need to persist?

```
signalk:    
  image: signalk/signalk-server:v1.40.0        
  ...
  volumes:
  - signalk-data:/home/node/.signalk
  - ${USERDIR}/docker/signalk/settings.json:/home/node/.signalk/settings.json:rw
```
